# Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
import numpy as np

In [12]:
def fnVander(x,N):
    a=np.column_stack([x**(N-1-i) for i in range(N)])
    return a
    

In [20]:
x=np.array([1,2,3,4])
N=5
fnVander(x,5)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]], dtype=int32)

# Vandermonde function with increasing boolean argument.

In [8]:
#final func
def fnVanderinc(*arg,inc):
    if(inc==False or inc==""):
        a=np.column_stack([x**(N-1-i) for i in range(N)])
        return a
    else:
        a=np.column_stack([x**(N-i) for i in range(N,0,-1)])
        return a

In [9]:
x=np.array([1,2,3])
N=4
fnVanderinc(x,N,inc=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27]], dtype=int32)

In [37]:
x=np.array([1,2,3])
N=4
fnVanderinc(x,N,inc="")


array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1]], dtype=int32)

In [38]:
x=np.array([1,2,3])
N=4
fnVanderinc(x,N,inc=False)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1]], dtype=int32)

# Problem Statement 2: Moving Average

In [ ]:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [17]:
def movingAvg(x,wind):
    n=len(x)
    for i in range(0,n-wind+1):
        sums=0
        for j in range(i,i+wind):
            sums=sums+x[j]
        avg=sums/wind
        print(avg)    

In [18]:
x=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
movingAvg(x,3)

5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333


In [19]:
x=np.array([10,20,30,40,50,60,70,80,90,100])
movingAvg(x,4)

25.0
35.0
45.0
55.0
65.0
75.0
85.0
